services:
  db:
    image: postgres:17.1
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=pet-markt
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: